# Generated by Django 4.1.5 on 2023-07-19 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('paper_type', models.CharField(choices=[('Mid', 'Mid Semester'), ('End', 'End Semester'), ('Quiz1', 'First Quiz'), ('Quiz2', 'Second Quiz')], default='mid', max_length=5)),
                ('pdf_file', models.FileField(upload_to='question_papers/')),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prevyear.subject')),
            ],
        ),
    ]
