# Generated by Django 4.1.5 on 2023-07-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobnews_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
