# Generated by Django 4.1.5 on 2023-07-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_details_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
